apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.zookeeper.service.serverPort }}
      targetPort: server
      protocol: TCP
      name: server
    - port: {{ .Values.zookeeper.service.leaderElectionPort }}
      targetPort: leader-election
      protocol: TCP
      name: leader-election
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.zookeeper.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.zookeeper.service.serverPort }}
      targetPort: server
      protocol: TCP
      name: server
    - port: {{ .Values.zookeeper.service.leaderElectionPort }}
      targetPort: leader-election
      protocol: TCP
      name: leader-election
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
